# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-11 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='hosts',
        ),
        migrations.RemoveField(
            model_name='task',
            name='script_name',
        ),
    ]
